#!/usr/bin/python3

def fizzbuzz():
    for num in range(100):
        if ((num % 5 == 0) & (num % 3 == 0)):
            return("FizzBuzz")
        elif (num % 5 == 0):
            return("Buzz")
        elif (num % 3 == 0):
            return("Fizz")
        else:
            return(num)
    print(num)
